src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use ApiPlatform\Core\Annotation\ApiFilter;
use Doctrine\Common\Collections\Collection;
use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Security\Core\User\UserInterface;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\SearchFilter;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;


#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'Un compte existe déjà avec cette adresse email.')]
// #[ApiFilter(SearchFilter::class, properties: ['id' => 'exact', 'price' => 'exact', 'description' => 'partial'])]
#[ApiResource(
    collectionOperations: [
        'get' => ['normalization_context' => ['groups' => 'user:item']],
        'post' => ['normalization_context' => ['groups' => 'user:item']],
    ],
    itemOperations: [
        'get' => ['normalization_context' => ['groups' => 'user:item']],
        'put',
    ],
)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    #[Groups(["user:list", "user:item"])]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    #[Groups(["user:list", "user:item"])]
    private $email;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    private $password;

    #[ORM\OneToMany(mappedBy: 'owner', targetEntity: Playlist::class)]
    private $playlists;

    #[ORM\ManyToMany(targetEntity: Song::class, inversedBy: 'users_loved')]
    #[Groups(["user:list", "user:item", "user:post:item"])]
    private $loved_songs;

    public function __construct()
    {
        $this->playlists = new ArrayCollection();
        $this->loved_songs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection<int, Playlist>
     */
    public function getPlaylists(): Collection
    {
        return $this->playlists;
    }

    public function addPlaylist(Playlist $playlist): self
    {
        if (!$this->playlists->contains($playlist)) {
            $this->playlists[] = $playlist;
            $playlist->setOwner($this);
        }

        return $this;
    }

    public function removePlaylist(Playlist $playlist): self
    {
        if ($this->playlists->removeElement($playlist)) {
            // set the owning side to null (unless already changed)
            if ($playlist->getOwner() === $this) {
                $playlist->setOwner(null);
            }
        }

        return $this;
    }

    public function __toString(){
        // to show the name of the Category in the select
        return $this->email;
        // to show the id of the Category in the select
        // return $this->id;
    }

    /**
     * @return Collection<int, Song>
     */
    public function getLovedSongs(): Collection
    {
        return $this->loved_songs;
    }

    public function addLovedSong(Song $lovedSong): self
    {
        if (!$this->loved_songs->contains($lovedSong)) {
            $this->loved_songs[] = $lovedSong;
        }

        return $this;
    }

    public function removeLovedSong(Song $lovedSong): self
    {
        $this->loved_songs->removeElement($lovedSong);

        return $this;
    }

    public function promote(User $user): self {
        $this->setRoles(['ROLE_ADMIN']);
        return $this;
    }
}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}Se connecter{% endblock %}

{% block body %}
<div class="container center">
    <form method="post">


        <h1>Se connecter</h1>
        {% if error %}
            <p class="error subtitle" style="margin-bottom: 2em;">{{ error.messageKey|trans(error.messageData, 'security') }}</p>
        {% endif %}
        {% if app.user %}
            <div class="error">
                <p style="margin-bottom: 2em;">Vous êtes déjà connecté en tant que {{ app.user.username }}, <a href="{{ path('app_logout') }}">Se déconnecter</a></p> 
            </div>
        {% endif %}
        <p class="subtitle">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut imperdiet ex id diam congue, quis dapibus neque aliquet. Proin rutrum egestas nisi eget viverra. Donec lacinia diam id nisi vulputate.</p>
        <label for="inputEmail">Adresse email:</label>
        <input type="email" value="{{ last_username }}" placeholder="Adresse email" name="email" id="inputEmail" class="form-input" autocomplete="email" required autofocus>
        <label for="inputPassword">Mot de passe:</label>
        <input type="password" name="password" id="inputPassword" placeholder="Mot de passe" class="form-input" autocomplete="current-password" required>

        <input type="hidden" name="_csrf_token"
            value="{{ csrf_token('authenticate') }}"
        >

        <div class="checkbox">
            <label>
                <input type="checkbox" name="_remember_me"> Se souvenir de moi ?
            </label>
        </div>

        <button class="" type="submit">
            Sign in
        </button>
    </form>
</div>
{% endblock %}