src/Entity/Playlist.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\PlaylistRepository;
use ApiPlatform\Core\Annotation\ApiFilter;
use Doctrine\Common\Collections\Collection;
use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Serializer\Annotation\Groups;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\SearchFilter;

#[ORM\Entity(repositoryClass: PlaylistRepository::class)]
#[ApiResource(
    collectionOperations: ['get' => ['normalization_context' => ['groups' => 'playlist:list', 'enable_max_depth' => true]]],
    itemOperations: ['get' => ['normalization_context' => ['groups' => 'playlist:item', 'enable_max_depth' => true]]],
)]
class Playlist
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    #[Groups(["playlist:list", "playlist:item", "song:list", "song:item", "artist:list", "artist:item"])]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $type;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    #[Groups(["playlist:list", "playlist:item", "song:list", "song:item", "artist:list", "artist:item"])]
    private $image;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'playlists')]
    private $owner;

    #[ORM\ManyToOne(targetEntity: Artist::class, inversedBy: 'albums')]
    #[Groups(["playlist:list", "playlist:item", "song:list", "song:item"])]
    private $artist;

    #[ORM\Column(type: 'string', length: 255)]
    #[Groups(["playlist:list", "playlist:item", "song:list", "song:item"])]
    private $title;

    #[ORM\ManyToMany(targetEntity: Song::class, mappedBy: 'playlist')]
    #[Groups(["playlist:list", "playlist:item"])]
    private $songs;

    #[ORM\Column(type: 'date', nullable: true)]
    #[Groups(["playlist:list", "playlist:item", "song:list", "song:item"])]
    private $date;

    public function __construct()
    {
        $this->date = new \DateTime();
        $this->songs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getOwner(): ?User
    {
        return $this->owner;
    }

    public function setOwner(?User $owner): self
    {
        $this->owner = $owner;

        return $this;
    }

    public function getArtist(): ?Artist
    {
        return $this->artist;
    }

    public function setArtist(?Artist $artist): self
    {
        $this->artist = $artist;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function __toString(){
        // to show the name of the Category in the select
        return $this->title;
        // to show the id of the Category in the select
        // return $this->id;
    }

    /**
     * @return Collection<int, Song>
     */
    public function getSongs(): Collection
    {
        return $this->songs;
    }

    public function addSong(Song $song): self
    {
        if (!$this->songs->contains($song)) {
            $this->songs[] = $song;
            $song->addPlaylist($this);
        }

        return $this;
    }

    public function removeSong(Song $song): self
    {
        if ($this->songs->removeElement($song)) {
            $song->removePlaylist($this);
        }

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use ApiPlatform\Core\Annotation\ApiFilter;
use Doctrine\Common\Collections\Collection;
use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Security\Core\User\UserInterface;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\SearchFilter;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;


#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'Un compte existe déjà avec cette adresse email.')]
// #[ApiFilter(SearchFilter::class, properties: ['id' => 'exact', 'price' => 'exact', 'description' => 'partial'])]
#[ApiResource(
    collectionOperations: [
        'get' => ['normalization_context' => ['groups' => 'user:item']],
        'post' => ['normalization_context' => ['groups' => 'user:item']],
    ],
    itemOperations: [
        'get' => ['normalization_context' => ['groups' => 'user:item']],
        'put',
    ],
)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    #[Groups(["user:list", "user:item"])]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    #[Groups(["user:list", "user:item"])]
    private $email;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    private $password;

    #[ORM\OneToMany(mappedBy: 'owner', targetEntity: Playlist::class)]
    private $playlists;

    #[ORM\ManyToMany(targetEntity: Song::class, inversedBy: 'users_loved')]
    #[Groups(["user:list", "user:item", "user:post:item"])]
    private $loved_songs;

    public function __construct()
    {
        $this->playlists = new ArrayCollection();
        $this->loved_songs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection<int, Playlist>
     */
    public function getPlaylists(): Collection
    {
        return $this->playlists;
    }

    public function addPlaylist(Playlist $playlist): self
    {
        if (!$this->playlists->contains($playlist)) {
            $this->playlists[] = $playlist;
            $playlist->setOwner($this);
        }

        return $this;
    }

    public function removePlaylist(Playlist $playlist): self
    {
        if ($this->playlists->removeElement($playlist)) {
            // set the owning side to null (unless already changed)
            if ($playlist->getOwner() === $this) {
                $playlist->setOwner(null);
            }
        }

        return $this;
    }

    public function __toString(){
        // to show the name of the Category in the select
        return $this->email;
        // to show the id of the Category in the select
        // return $this->id;
    }

    /**
     * @return Collection<int, Song>
     */
    public function getLovedSongs(): Collection
    {
        return $this->loved_songs;
    }

    public function addLovedSong(Song $lovedSong): self
    {
        if (!$this->loved_songs->contains($lovedSong)) {
            $this->loved_songs[] = $lovedSong;
        }

        return $this;
    }

    public function removeLovedSong(Song $lovedSong): self
    {
        $this->loved_songs->removeElement($lovedSong);

        return $this;
    }

    public function promote(User $user): self {
        $this->setRoles(['ROLE_ADMIN']);
        return $this;
    }
}

src/Form/PlaylistType.php
<?php

namespace App\Form;

use App\Entity\Artist;
use App\Entity\Playlist;
use App\Repository\ArtistRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;

class PlaylistType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('type', HiddenType::class, [
                'required'   => false,
                'empty_data' => 'Album',
            ])
            ->add('title', TextType::class)
            ->add('date', DateType::class, [
                'data' => new \DateTime()
            ])
            ->add('image', FileType::class, [
                'label' => 'Ajouter une image',

                // unmapped means that this field is not associated to any entity property
                'mapped' => false,

                // make it optional so you don't have to re-upload the PDF file
                // every time you edit the Product details
                'required' => false
            ])
            ->add('artist', EntityType::class, [
                'class' => Artist::class,
                'query_builder' => function (ArtistRepository $er) {
                    return $er->createQueryBuilder('a')
                        ->orderBy('a.id', 'ASC');
                },
                'choice_label' => 'name',
                'multiple' => false
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Playlist::class,
        ]);
    }
}

src/Controller/PlaylistController.php
<?php

namespace App\Controller;

use App\Entity\Playlist;
use App\Form\PlaylistType;
use App\Repository\PlaylistRepository;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/playlist')]
class PlaylistController extends AbstractController
{
    #[Route('/', name: 'app_playlist_index', methods: ['GET'])]
    public function index(PlaylistRepository $playlistRepository): Response
    {
        return $this->render('playlist/index.html.twig', [
            'playlists' => $playlistRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_playlist_new', methods: ['GET', 'POST'])]
    public function new(Request $request, PlaylistRepository $playlistRepository): Response
    {
        $playlist = new Playlist();
        $form = $this->createForm(PlaylistType::class, $playlist);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $file = $form['image']->getData();
            $extension = $file->guessExtension();
            $directory = $this->getParameter('kernel.project_dir').'/public/albums/'. $form['title']->getData();
            $filename = str_replace(' ', '_', $form['title']->getData()) . '.' . $extension;
            
            $file->move($directory, $filename);
            $playlist->setImage($filename);
            $playlistRepository->add($playlist);
            return $this->redirectToRoute('app_playlist_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('playlist/new.html.twig', [
            'playlist' => $playlist,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_playlist_show', methods: ['GET'])]
    public function show(Playlist $playlist): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $user = $this->get('security.token_storage')->getToken()->getUser();
        return $this->render('base.html.twig', [ // RENDERED IN VUE
            'playlist' => $playlist,
            'user' => $user
        ]);
    }

    #[Route('/{id}/edit', name: 'app_playlist_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Playlist $playlist, PlaylistRepository $playlistRepository): Response
    {
        $form = $this->createForm(PlaylistType::class, $playlist);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $file = $form['image']->getData();
            if($file) {
                $extension = $file->guessExtension();
                $directory = $this->getParameter('kernel.project_dir').'/public/albums/'. $form['title']->getData();
                $filename = str_replace(' ', '_', $form['title']->getData()) . '.' . $extension;
                
                $file->move($directory, $filename);
                $playlist->setImage($filename);
            }
            $playlistRepository->add($playlist);
            return $this->redirectToRoute('app_playlist_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('playlist/edit.html.twig', [
            'playlist' => $playlist,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_playlist_delete', methods: ['POST'])]
    public function delete(Request $request, Playlist $playlist, PlaylistRepository $playlistRepository): Response
    {

        if ($this->isCsrfTokenValid('delete'.$playlist->getId(), $request->request->get('_token'))) {
            $playlistRepository->remove($playlist);
            $directory = $this->getParameter('kernel.project_dir').'/public/images/albums/';
            $filename = $directory . '.' . $playlist->getImage();
            $filesystem = new Filesystem();
            $filesystem->remove($filename);
        }

        return $this->redirectToRoute('app_playlist_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/playlist/_delete_form.html.twig
<form method="post" action="{{ path('app_playlist_delete', {'id': playlist.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ playlist.id) }}">
    <button class="btn">Supprimer</button>
</form>

templates/playlist/_form.html.twig
{{ form_start(form) }}
    <label for="image">Titre:</label><br>
    {{ form_widget(form.title) }}
    <label for="image">Image:</label><br>
    {{ form_widget(form.image) }}<br><br>
    <label for="image">Artiste:</label><br>
    {{ form_widget(form.artist) }}
    <label for="image">Date de sortie:</label><br>
    {{ form_widget(form.date) }}
    <button class="" type="submit">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/playlist/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Playlist{% endblock %}

{% block body %}
<div class="container center">
    <h1>Modifier l'album</h1>>
    {{ include('playlist/_form.html.twig', {'button_label': 'Modifier'}) }}
    {{ include('playlist/_delete_form.html.twig') }}
    <p><a href="{{ path('app_playlist_index') }}">Retour</a></p>
</div>
{% endblock %}

templates/playlist/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestion des albums{% endblock %}

{% block body %}
<div class="container crud-container center" style="justify-content: flex-start">
    <h1>Gestion des albums</h1>
    <table class="crud">
        <thead>
            <tr>
                <th>Artiste</th>
                <th>Album</th>
                <th>Date de sortie</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for playlist in playlists %}
            <tr>
                <td>
                    <a href="{{ path('app_artist_show', {'id': playlist.artist.id}) }}">
                        {{ playlist.artist.name }}<br>
                        <img src="{{ asset('artists/' ~ playlist.artist.name ~ '/' ~ playlist.artist.image)}}">
                    </a>
                <td>
                    <a href="{{ path('app_playlist_show', {'id': playlist.id}) }}">
                        {{ playlist.title }}<br>
                        <img src="{{ asset('albums/' ~ playlist.title ~ '/' ~ playlist.image)}}">
                    </a>
                </td>
                <td>
                    {{ playlist.date|format_datetime(locale='fr',pattern="EEEE dd MMMM YYYY") }}
                </td>
                <td>
                    <button class="small">
                        <a href="{{ path('app_playlist_edit', {'id': playlist.id}) }}">Modifier</a>
                    </button>
                    <button class="small">
                        <a href="{{ path('app_playlist_delete', {'id': playlist.id}) }}">Supprimer</a>
                    </button>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">Pas d'albums trouvé.</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <button type="submit">
        <a href="{{ path('app_playlist_new') }}">Ajouter un album</a>
    </button>
</div>
{% endblock %}

templates/playlist/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un album{% endblock %}

{% block body %}
    <div class="container center">
    <h1>Ajouter un album</h1>

    {{ include('playlist/_form.html.twig') }}

    <p><a href="{{ path('app_playlist_index') }}">Retour</a></p>
    </div>
{% endblock %}

templates/playlist/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Playlist{% endblock %}

{% block body %}
    <div class="playlist">
        <div class="playlist-description">
            <img src="{{ asset('albums/' ~ playlist.title ~ '/' ~ playlist.image) }}">
            <div class="playlist-description-infos">
                <a href="{{ path('app_artist_show', {'id': playlist.artist.id}) }}">
                    <h1>{{ playlist.title }}</h1>
                    <div class="artist">
                        <img src="{{ asset('artists/' ~ playlist.artist.name ~ '/' ~ playlist.artist.image) }}">
                        <h3>{{ playlist.artist.name }}</h3>
                    </div>
                    <p class="caption"><b>{{ playlist.songs|length }} </b> musiques</p>
                    <p class="caption">Sorti le <b>{{ playlist.date|format_datetime(locale='fr',pattern="EEEE dd MMMM YYYY") }}</b></p>
                </a>
            </div>
        </div>
        <table class="songs">
        <thead>
            <tr>
                <th>
                    #
                </th>
                <th>
                    Titre
                </th>
                <th>
                    Actions
                </th>
            </tr>
        </thead>
        <tbody>
            {% for song in playlist.songs %}
            <tr>
                <td>
                    {{ loop.index }}
                </td>
                <td>
                    {{ song.title }}
                </td>
                <td>
                    <a>
                        <span class="material-icons">play_arrow</span>
                    </a>
                        {% if song in user.lovedSongs %}
                            {# ROUTE NO EXIST (VUE PART) #}
                            {# <a href="{{ path('remove_loved_track', {'id': song.id, 'path': app.request.uri}) }}"> #}
                                <span class="material-icons selected">local_fire_department</span>
                            {# </a> #}
                        {% else %}
                            {# <a href="{{ path('add_loved_track', {'id': song.id}) }}"> #}
                                <span class="material-icons">local_fire_department</span>
                            {# </a> #}
                        {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
        </table>
    </div>
{% endblock %}